package:
  name: pymeteo
  version: "1.0.3"

build:
  number: 1
  script: python setup.py install

source:
  git_url: https://github.com/cwebster2/pyMeteo.git

requirements:
  build:
    - python

  run:
    - python=3.10
    - pyqt=5.15.7
    - numpy=1.23.2
    - matplotlib=3.5.3
    - hdf5=3.7.0

about:
  home: https://github.com/cwebster2/pyMeteo
  license: BSD3
  license_file: LICENSE
  summary: General meteorological routines, skew-T/log-p plotting and working with CM1 model data.

extra:
  maintainers:
    - Casey Webster <casey@wxster.com>
